import type { Metadata } from 'next';
import Link from 'next/link';
import { Inter as FontSans } from 'next/font/google';
import { Menu } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Sheet, SheetContent, SheetTrigger } from '@/components/ui/sheet';
import { DefaultNavbar, DrawerNavbar } from '@/components/layout/navbar';
import NavbarLeftPortion from '@/components/layout/navbar-left-portion';
import { cn } from '@/lib/utils';

import './globals.css';

const fontSans = FontSans({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable
        )}
      >
        <header className="sticky top-0 flex h-16 items-center gap-4 border-b bg-background px-4 md:px-6">
          <DefaultNavbar />
          <Sheet>
            <SheetTrigger asChild>
              <Button
                variant="outline"
                size="icon"
                className="shrink-0 md:hidden"
              >
                <Menu className="h-5 w-5" />
                <span className="sr-only">Toggle navigation menu</span>
              </Button>
            </SheetTrigger>
            <SheetContent side="left">
              <DrawerNavbar />
            </SheetContent>
          </Sheet>
          <div className="flex w-full gap-2 items-center justify-end md:ml-auto">
            <NavbarLeftPortion />
          </div>
        </header>
        <main className="min-h-[calc(100vh_-_theme(spacing.16))] flex-1 bg-muted/40 p-4 md:p-10">
          {children}
        </main>
      </body>
    </html>
  );
}
